"use client"
import CognizantLogo from "@/app/demo/layout1/logos/cognizant-logo";
import {useEffect} from "react";

export default function CognizantSection({className}) {

    let cognizantLogo;
    let animateElements;
    let animateTransformElements;

    useEffect(()=>{
        cognizantLogo = document.getElementById("cognizantLogo")
        animateElements = cognizantLogo.querySelectorAll("animate");
        animateTransformElements = cognizantLogo.querySelectorAll("animateTransform");
    },[])

    const onClick = ()=>{

        animateElements.forEach((element) => {
            element.beginElement()
        });

        animateTransformElements.forEach((element) => {
            element.beginElement()
        });

    }
    return (<>
        <div>
            <div className="sm:mx-[31%] mx-[9%]">
                <CognizantLogo
                    onClick={onClick}
                    className="w-96 sm:mt-28 mt-24 -mb-12 "
                    width="500"
                    height="150"
                />
            </div>
            <div className="text-white p-8 text-justify bg-[#0a60c2]">
                <div className="text-center -mt-4 mb-4 text-gray-300 text-sm">[ 04/2019 - 12/2019 ]</div>
                <p>
                    Cognizant was a great opportunity to grow! I got my first exposure to leading a team
                    as we built a proof of concept that would allow developers to deploy code that was generated by Maven
                    Archetypes
                    through a web app with some basic information. After we finished integrating this product
                    with both Azure and GitLab, I joined another team to finish building another web app that
                    managed research documents for our client. Though I added services to multiple parts of the
                    application,
                    I primarily focused on building out the notification service triggered by events such as approvals,
                    review requests, denials, etc.
                </p>
                <div className="mt-8 text-center">
                    <h3 className="font-extrabold mb-4">Tech / Skills</h3>
                    <div>
                        Java &#9679; Spring Boot &#9679; Full Stack &#9679; Angular &#9679; CSS &#9679; System
                        Design &#9679; Microservices &#9679; Pivotal
                        Cloud Foundry &#9679; SQL
                    </div>
                </div>
            </div>

        </div>
    </>);
}